CXX=g++
CFLAGS=-Wall
LDFLAGS=-lpthread

TARGET=Singleton
SOURCES=main.cpp
#HEADERS=Singleton.h Application.h

$(TARGET):
#	$(CXX) $(CFLAGS) $(SOURCES) $(HEADERS) -o $@ $(LDFLAGS)
	$(CXX) $(CFLAGS) $(SOURCES) -o $@ $(LDFLAGS)

clean:
	rm -f *.o $(TARGET)
